<?php $helper = $this->helper('Openpay\Widgets\Helper\Data'); ?>
<?php if($helper->isEnabled()): ?>
	<?php if($helper->isCartWidgetEnabled()): ?>
		<?php $grandTotal = $block->getQuote()->getGrandTotal() ?>
		
		<div class="opycart"><opy-cart amount="<?= $grandTotal ?>" logo="<?= $helper->getCartLogo() ?>" more-info-text="<?= $helper->getCartWidgetLearnMoreText() ?>" info-icon="<?= $helper->getCartWidgetInfoIcon() ?>"></opy-cart></div>
	<?php endif; ?>
<?php endif; ?>